# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseClassifier": "00_base_model.ipynb",
         "TimmModelClassifier": "00_base_model.ipynb",
         "ClipModelClassifier": "00_base_model.ipynb",
         "model_factory": "00_base_model.ipynb",
         "test": "00_base_model.ipynb",
         "LitModel": "01_lit_model.ipynb",
         "get_trainer": "01_lit_model.ipynb",
         "DEFAULT_HPARAMS": "01_lit_model.ipynb"}

modules = ["base_model.py",
           "lit_model.py"]

doc_url = "https://anhvth.github.io/lit_classifier/"

git_url = "https://github.com/anhvth/lit_classifier/tree/main/"

def custom_doc_links(name): return None
