# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://anhvth.github.io/lit_classifier/"

git_url = "https://github.com/anhvth/lit_classifier/tree/main/"

def custom_doc_links(name): return None
